/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as SimulationGeneratorRouteImport } from './routes/simulation-generator'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MySimulationsRouteImport } from './routes/my-simulations'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as AiAgentRouteImport } from './routes/ai-agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectsClassIdRouteImport } from './routes/subjects.$classId'
import { Route as SimulationTopicRouteImport } from './routes/simulation.$topic'
import { Route as SandboxSimulationIdRouteImport } from './routes/sandbox.$simulationId'
import { Route as FormulaLabTopicRouteImport } from './routes/formula-lab.$topic'
import { Route as ChaptersClassIdSubjectRouteImport } from './routes/chapters.$classId.$subject'
import { Route as TopicsClassIdSubjectChapterRouteImport } from './routes/topics.$classId.$subject.$chapter'
import { Route as SimulationClass9PhysicsLawsOfMotionRouteImport } from './routes/simulation.class9.physics.laws-of-motion'
import { Route as SimulationClass9PhysicsLawsOfMotionProjectileMotionRouteImport } from './routes/simulation.class9.physics.laws-of-motion.projectile-motion'

const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationGeneratorRoute = SimulationGeneratorRouteImport.update({
  id: '/simulation-generator',
  path: '/simulation-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MySimulationsRoute = MySimulationsRouteImport.update({
  id: '/my-simulations',
  path: '/my-simulations',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentRoute = AiAgentRouteImport.update({
  id: '/ai-agent',
  path: '/ai-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsClassIdRoute = SubjectsClassIdRouteImport.update({
  id: '/subjects/$classId',
  path: '/subjects/$classId',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationTopicRoute = SimulationTopicRouteImport.update({
  id: '/simulation/$topic',
  path: '/simulation/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxSimulationIdRoute = SandboxSimulationIdRouteImport.update({
  id: '/sandbox/$simulationId',
  path: '/sandbox/$simulationId',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulaLabTopicRoute = FormulaLabTopicRouteImport.update({
  id: '/formula-lab/$topic',
  path: '/formula-lab/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersClassIdSubjectRoute = ChaptersClassIdSubjectRouteImport.update({
  id: '/chapters/$classId/$subject',
  path: '/chapters/$classId/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsClassIdSubjectChapterRoute =
  TopicsClassIdSubjectChapterRouteImport.update({
    id: '/topics/$classId/$subject/$chapter',
    path: '/topics/$classId/$subject/$chapter',
    getParentRoute: () => rootRouteImport,
  } as any)
const SimulationClass9PhysicsLawsOfMotionRoute =
  SimulationClass9PhysicsLawsOfMotionRouteImport.update({
    id: '/simulation/class9/physics/laws-of-motion',
    path: '/simulation/class9/physics/laws-of-motion',
    getParentRoute: () => rootRouteImport,
  } as any)
const SimulationClass9PhysicsLawsOfMotionProjectileMotionRoute =
  SimulationClass9PhysicsLawsOfMotionProjectileMotionRouteImport.update({
    id: '/projectile-motion',
    path: '/projectile-motion',
    getParentRoute: () => SimulationClass9PhysicsLawsOfMotionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-agent': typeof AiAgentRoute
  '/favorites': typeof FavoritesRoute
  '/library': typeof LibraryRoute
  '/my-simulations': typeof MySimulationsRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/simulation-generator': typeof SimulationGeneratorRoute
  '/tutor': typeof TutorRoute
  '/formula-lab/$topic': typeof FormulaLabTopicRoute
  '/sandbox/$simulationId': typeof SandboxSimulationIdRoute
  '/simulation/$topic': typeof SimulationTopicRoute
  '/subjects/$classId': typeof SubjectsClassIdRoute
  '/chapters/$classId/$subject': typeof ChaptersClassIdSubjectRoute
  '/simulation/class9/physics/laws-of-motion': typeof SimulationClass9PhysicsLawsOfMotionRouteWithChildren
  '/topics/$classId/$subject/$chapter': typeof TopicsClassIdSubjectChapterRoute
  '/simulation/class9/physics/laws-of-motion/projectile-motion': typeof SimulationClass9PhysicsLawsOfMotionProjectileMotionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-agent': typeof AiAgentRoute
  '/favorites': typeof FavoritesRoute
  '/library': typeof LibraryRoute
  '/my-simulations': typeof MySimulationsRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/simulation-generator': typeof SimulationGeneratorRoute
  '/tutor': typeof TutorRoute
  '/formula-lab/$topic': typeof FormulaLabTopicRoute
  '/sandbox/$simulationId': typeof SandboxSimulationIdRoute
  '/simulation/$topic': typeof SimulationTopicRoute
  '/subjects/$classId': typeof SubjectsClassIdRoute
  '/chapters/$classId/$subject': typeof ChaptersClassIdSubjectRoute
  '/simulation/class9/physics/laws-of-motion': typeof SimulationClass9PhysicsLawsOfMotionRouteWithChildren
  '/topics/$classId/$subject/$chapter': typeof TopicsClassIdSubjectChapterRoute
  '/simulation/class9/physics/laws-of-motion/projectile-motion': typeof SimulationClass9PhysicsLawsOfMotionProjectileMotionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-agent': typeof AiAgentRoute
  '/favorites': typeof FavoritesRoute
  '/library': typeof LibraryRoute
  '/my-simulations': typeof MySimulationsRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/simulation-generator': typeof SimulationGeneratorRoute
  '/tutor': typeof TutorRoute
  '/formula-lab/$topic': typeof FormulaLabTopicRoute
  '/sandbox/$simulationId': typeof SandboxSimulationIdRoute
  '/simulation/$topic': typeof SimulationTopicRoute
  '/subjects/$classId': typeof SubjectsClassIdRoute
  '/chapters/$classId/$subject': typeof ChaptersClassIdSubjectRoute
  '/simulation/class9/physics/laws-of-motion': typeof SimulationClass9PhysicsLawsOfMotionRouteWithChildren
  '/topics/$classId/$subject/$chapter': typeof TopicsClassIdSubjectChapterRoute
  '/simulation/class9/physics/laws-of-motion/projectile-motion': typeof SimulationClass9PhysicsLawsOfMotionProjectileMotionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-agent'
    | '/favorites'
    | '/library'
    | '/my-simulations'
    | '/profile'
    | '/progress'
    | '/settings'
    | '/simulation-generator'
    | '/tutor'
    | '/formula-lab/$topic'
    | '/sandbox/$simulationId'
    | '/simulation/$topic'
    | '/subjects/$classId'
    | '/chapters/$classId/$subject'
    | '/simulation/class9/physics/laws-of-motion'
    | '/topics/$classId/$subject/$chapter'
    | '/simulation/class9/physics/laws-of-motion/projectile-motion'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-agent'
    | '/favorites'
    | '/library'
    | '/my-simulations'
    | '/profile'
    | '/progress'
    | '/settings'
    | '/simulation-generator'
    | '/tutor'
    | '/formula-lab/$topic'
    | '/sandbox/$simulationId'
    | '/simulation/$topic'
    | '/subjects/$classId'
    | '/chapters/$classId/$subject'
    | '/simulation/class9/physics/laws-of-motion'
    | '/topics/$classId/$subject/$chapter'
    | '/simulation/class9/physics/laws-of-motion/projectile-motion'
  id:
    | '__root__'
    | '/'
    | '/ai-agent'
    | '/favorites'
    | '/library'
    | '/my-simulations'
    | '/profile'
    | '/progress'
    | '/settings'
    | '/simulation-generator'
    | '/tutor'
    | '/formula-lab/$topic'
    | '/sandbox/$simulationId'
    | '/simulation/$topic'
    | '/subjects/$classId'
    | '/chapters/$classId/$subject'
    | '/simulation/class9/physics/laws-of-motion'
    | '/topics/$classId/$subject/$chapter'
    | '/simulation/class9/physics/laws-of-motion/projectile-motion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAgentRoute: typeof AiAgentRoute
  FavoritesRoute: typeof FavoritesRoute
  LibraryRoute: typeof LibraryRoute
  MySimulationsRoute: typeof MySimulationsRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  SettingsRoute: typeof SettingsRoute
  SimulationGeneratorRoute: typeof SimulationGeneratorRoute
  TutorRoute: typeof TutorRoute
  FormulaLabTopicRoute: typeof FormulaLabTopicRoute
  SandboxSimulationIdRoute: typeof SandboxSimulationIdRoute
  SimulationTopicRoute: typeof SimulationTopicRoute
  SubjectsClassIdRoute: typeof SubjectsClassIdRoute
  ChaptersClassIdSubjectRoute: typeof ChaptersClassIdSubjectRoute
  SimulationClass9PhysicsLawsOfMotionRoute: typeof SimulationClass9PhysicsLawsOfMotionRouteWithChildren
  TopicsClassIdSubjectChapterRoute: typeof TopicsClassIdSubjectChapterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation-generator': {
      id: '/simulation-generator'
      path: '/simulation-generator'
      fullPath: '/simulation-generator'
      preLoaderRoute: typeof SimulationGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-simulations': {
      id: '/my-simulations'
      path: '/my-simulations'
      fullPath: '/my-simulations'
      preLoaderRoute: typeof MySimulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agent': {
      id: '/ai-agent'
      path: '/ai-agent'
      fullPath: '/ai-agent'
      preLoaderRoute: typeof AiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$classId': {
      id: '/subjects/$classId'
      path: '/subjects/$classId'
      fullPath: '/subjects/$classId'
      preLoaderRoute: typeof SubjectsClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation/$topic': {
      id: '/simulation/$topic'
      path: '/simulation/$topic'
      fullPath: '/simulation/$topic'
      preLoaderRoute: typeof SimulationTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox/$simulationId': {
      id: '/sandbox/$simulationId'
      path: '/sandbox/$simulationId'
      fullPath: '/sandbox/$simulationId'
      preLoaderRoute: typeof SandboxSimulationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formula-lab/$topic': {
      id: '/formula-lab/$topic'
      path: '/formula-lab/$topic'
      fullPath: '/formula-lab/$topic'
      preLoaderRoute: typeof FormulaLabTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/$classId/$subject': {
      id: '/chapters/$classId/$subject'
      path: '/chapters/$classId/$subject'
      fullPath: '/chapters/$classId/$subject'
      preLoaderRoute: typeof ChaptersClassIdSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$classId/$subject/$chapter': {
      id: '/topics/$classId/$subject/$chapter'
      path: '/topics/$classId/$subject/$chapter'
      fullPath: '/topics/$classId/$subject/$chapter'
      preLoaderRoute: typeof TopicsClassIdSubjectChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation/class9/physics/laws-of-motion': {
      id: '/simulation/class9/physics/laws-of-motion'
      path: '/simulation/class9/physics/laws-of-motion'
      fullPath: '/simulation/class9/physics/laws-of-motion'
      preLoaderRoute: typeof SimulationClass9PhysicsLawsOfMotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation/class9/physics/laws-of-motion/projectile-motion': {
      id: '/simulation/class9/physics/laws-of-motion/projectile-motion'
      path: '/projectile-motion'
      fullPath: '/simulation/class9/physics/laws-of-motion/projectile-motion'
      preLoaderRoute: typeof SimulationClass9PhysicsLawsOfMotionProjectileMotionRouteImport
      parentRoute: typeof SimulationClass9PhysicsLawsOfMotionRoute
    }
  }
}

interface SimulationClass9PhysicsLawsOfMotionRouteChildren {
  SimulationClass9PhysicsLawsOfMotionProjectileMotionRoute: typeof SimulationClass9PhysicsLawsOfMotionProjectileMotionRoute
}

const SimulationClass9PhysicsLawsOfMotionRouteChildren: SimulationClass9PhysicsLawsOfMotionRouteChildren =
  {
    SimulationClass9PhysicsLawsOfMotionProjectileMotionRoute:
      SimulationClass9PhysicsLawsOfMotionProjectileMotionRoute,
  }

const SimulationClass9PhysicsLawsOfMotionRouteWithChildren =
  SimulationClass9PhysicsLawsOfMotionRoute._addFileChildren(
    SimulationClass9PhysicsLawsOfMotionRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAgentRoute: AiAgentRoute,
  FavoritesRoute: FavoritesRoute,
  LibraryRoute: LibraryRoute,
  MySimulationsRoute: MySimulationsRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  SettingsRoute: SettingsRoute,
  SimulationGeneratorRoute: SimulationGeneratorRoute,
  TutorRoute: TutorRoute,
  FormulaLabTopicRoute: FormulaLabTopicRoute,
  SandboxSimulationIdRoute: SandboxSimulationIdRoute,
  SimulationTopicRoute: SimulationTopicRoute,
  SubjectsClassIdRoute: SubjectsClassIdRoute,
  ChaptersClassIdSubjectRoute: ChaptersClassIdSubjectRoute,
  SimulationClass9PhysicsLawsOfMotionRoute:
    SimulationClass9PhysicsLawsOfMotionRouteWithChildren,
  TopicsClassIdSubjectChapterRoute: TopicsClassIdSubjectChapterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
