/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AiAgentRouteImport } from './routes/ai-agent'
import { Route as ClassFeedRouteImport } from './routes/class-feed'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as InstitutionalRouteImport } from './routes/institutional'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SimulationsRouteImport } from './routes/simulations'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AdminSplatRouteImport } from './routes/admin.$'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as DemoAssetsRouteImport } from './routes/demo.assets'
import { Route as DemoSimulationRouteImport } from './routes/demo.simulation'
import { Route as FormulaLabTopicRouteImport } from './routes/formula-lab.$topic'
import { Route as InstitutionalSplatRouteImport } from './routes/institutional.$'
import { Route as SandboxSimulationIdRouteImport } from './routes/sandbox.$simulationId'
import { Route as SimulationTopicRouteImport } from './routes/simulation.$topic'
import { Route as SimulationsIndexRouteImport } from './routes/simulations.index'
import { Route as SimulationsCreateRouteImport } from './routes/simulations.create'
import { Route as StudentAttendanceRouteImport } from './routes/student.attendance'
import { Route as SubjectsClassIdRouteImport } from './routes/subjects.$classId'
import { Route as ChaptersClassIdSubjectRouteImport } from './routes/chapters.$classId.$subject'
import { Route as TopicsClassIdSubjectChapterRouteImport } from './routes/topics.$classId.$subject.$chapter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentRoute = AiAgentRouteImport.update({
  id: '/ai-agent',
  path: '/ai-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassFeedRoute = ClassFeedRouteImport.update({
  id: '/class-feed',
  path: '/class-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionalRoute = InstitutionalRouteImport.update({
  id: '/institutional',
  path: '/institutional',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationsRoute = SimulationsRouteImport.update({
  id: '/simulations',
  path: '/simulations',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const DemoAssetsRoute = DemoAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => DemoRoute,
} as any)
const DemoSimulationRoute = DemoSimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => DemoRoute,
} as any)
const FormulaLabTopicRoute = FormulaLabTopicRouteImport.update({
  id: '/formula-lab/$topic',
  path: '/formula-lab/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionalSplatRoute = InstitutionalSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => InstitutionalRoute,
} as any)
const SandboxSimulationIdRoute = SandboxSimulationIdRouteImport.update({
  id: '/sandbox/$simulationId',
  path: '/sandbox/$simulationId',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationTopicRoute = SimulationTopicRouteImport.update({
  id: '/simulation/$topic',
  path: '/simulation/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationsIndexRoute = SimulationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SimulationsRoute,
} as any)
const SimulationsCreateRoute = SimulationsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => SimulationsRoute,
} as any)
const StudentAttendanceRoute = StudentAttendanceRouteImport.update({
  id: '/student/attendance',
  path: '/student/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsClassIdRoute = SubjectsClassIdRouteImport.update({
  id: '/subjects/$classId',
  path: '/subjects/$classId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersClassIdSubjectRoute = ChaptersClassIdSubjectRouteImport.update({
  id: '/chapters/$classId/$subject',
  path: '/chapters/$classId/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsClassIdSubjectChapterRoute =
  TopicsClassIdSubjectChapterRouteImport.update({
    id: '/topics/$classId/$subject/$chapter',
    path: '/topics/$classId/$subject/$chapter',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-agent': typeof AiAgentRoute
  '/class-feed': typeof ClassFeedRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRouteWithChildren
  '/institutional': typeof InstitutionalRouteWithChildren
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/parent': typeof ParentRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/simulations': typeof SimulationsRouteWithChildren
  '/tutor': typeof TutorRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/users': typeof AdminUsersRoute
  '/demo/assets': typeof DemoAssetsRoute
  '/demo/simulation': typeof DemoSimulationRoute
  '/formula-lab/$topic': typeof FormulaLabTopicRoute
  '/institutional/$': typeof InstitutionalSplatRoute
  '/sandbox/$simulationId': typeof SandboxSimulationIdRoute
  '/simulation/$topic': typeof SimulationTopicRoute
  '/simulations/create': typeof SimulationsCreateRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/subjects/$classId': typeof SubjectsClassIdRoute
  '/simulations/': typeof SimulationsIndexRoute
  '/chapters/$classId/$subject': typeof ChaptersClassIdSubjectRoute
  '/topics/$classId/$subject/$chapter': typeof TopicsClassIdSubjectChapterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-agent': typeof AiAgentRoute
  '/class-feed': typeof ClassFeedRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRouteWithChildren
  '/institutional': typeof InstitutionalRouteWithChildren
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/parent': typeof ParentRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tutor': typeof TutorRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/users': typeof AdminUsersRoute
  '/demo/assets': typeof DemoAssetsRoute
  '/demo/simulation': typeof DemoSimulationRoute
  '/formula-lab/$topic': typeof FormulaLabTopicRoute
  '/institutional/$': typeof InstitutionalSplatRoute
  '/sandbox/$simulationId': typeof SandboxSimulationIdRoute
  '/simulation/$topic': typeof SimulationTopicRoute
  '/simulations/create': typeof SimulationsCreateRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/subjects/$classId': typeof SubjectsClassIdRoute
  '/simulations': typeof SimulationsIndexRoute
  '/chapters/$classId/$subject': typeof ChaptersClassIdSubjectRoute
  '/topics/$classId/$subject/$chapter': typeof TopicsClassIdSubjectChapterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-agent': typeof AiAgentRoute
  '/class-feed': typeof ClassFeedRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRouteWithChildren
  '/institutional': typeof InstitutionalRouteWithChildren
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/parent': typeof ParentRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/simulations': typeof SimulationsRouteWithChildren
  '/tutor': typeof TutorRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/users': typeof AdminUsersRoute
  '/demo/assets': typeof DemoAssetsRoute
  '/demo/simulation': typeof DemoSimulationRoute
  '/formula-lab/$topic': typeof FormulaLabTopicRoute
  '/institutional/$': typeof InstitutionalSplatRoute
  '/sandbox/$simulationId': typeof SandboxSimulationIdRoute
  '/simulation/$topic': typeof SimulationTopicRoute
  '/simulations/create': typeof SimulationsCreateRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/subjects/$classId': typeof SubjectsClassIdRoute
  '/simulations/': typeof SimulationsIndexRoute
  '/chapters/$classId/$subject': typeof ChaptersClassIdSubjectRoute
  '/topics/$classId/$subject/$chapter': typeof TopicsClassIdSubjectChapterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-agent'
    | '/class-feed'
    | '/dashboard'
    | '/demo'
    | '/institutional'
    | '/library'
    | '/login'
    | '/parent'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/simulations'
    | '/tutor'
    | '/unauthorized'
    | '/admin/$'
    | '/admin/users'
    | '/demo/assets'
    | '/demo/simulation'
    | '/formula-lab/$topic'
    | '/institutional/$'
    | '/sandbox/$simulationId'
    | '/simulation/$topic'
    | '/simulations/create'
    | '/student/attendance'
    | '/subjects/$classId'
    | '/simulations/'
    | '/chapters/$classId/$subject'
    | '/topics/$classId/$subject/$chapter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ai-agent'
    | '/class-feed'
    | '/dashboard'
    | '/demo'
    | '/institutional'
    | '/library'
    | '/login'
    | '/parent'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/tutor'
    | '/unauthorized'
    | '/admin/$'
    | '/admin/users'
    | '/demo/assets'
    | '/demo/simulation'
    | '/formula-lab/$topic'
    | '/institutional/$'
    | '/sandbox/$simulationId'
    | '/simulation/$topic'
    | '/simulations/create'
    | '/student/attendance'
    | '/subjects/$classId'
    | '/simulations'
    | '/chapters/$classId/$subject'
    | '/topics/$classId/$subject/$chapter'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai-agent'
    | '/class-feed'
    | '/dashboard'
    | '/demo'
    | '/institutional'
    | '/library'
    | '/login'
    | '/parent'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/simulations'
    | '/tutor'
    | '/unauthorized'
    | '/admin/$'
    | '/admin/users'
    | '/demo/assets'
    | '/demo/simulation'
    | '/formula-lab/$topic'
    | '/institutional/$'
    | '/sandbox/$simulationId'
    | '/simulation/$topic'
    | '/simulations/create'
    | '/student/attendance'
    | '/subjects/$classId'
    | '/simulations/'
    | '/chapters/$classId/$subject'
    | '/topics/$classId/$subject/$chapter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiAgentRoute: typeof AiAgentRoute
  ClassFeedRoute: typeof ClassFeedRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRouteWithChildren
  InstitutionalRoute: typeof InstitutionalRouteWithChildren
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  ParentRoute: typeof ParentRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SimulationsRoute: typeof SimulationsRouteWithChildren
  TutorRoute: typeof TutorRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  FormulaLabTopicRoute: typeof FormulaLabTopicRoute
  SandboxSimulationIdRoute: typeof SandboxSimulationIdRoute
  SimulationTopicRoute: typeof SimulationTopicRoute
  StudentAttendanceRoute: typeof StudentAttendanceRoute
  SubjectsClassIdRoute: typeof SubjectsClassIdRoute
  ChaptersClassIdSubjectRoute: typeof ChaptersClassIdSubjectRoute
  TopicsClassIdSubjectChapterRoute: typeof TopicsClassIdSubjectChapterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agent': {
      id: '/ai-agent'
      path: '/ai-agent'
      fullPath: '/ai-agent'
      preLoaderRoute: typeof AiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class-feed': {
      id: '/class-feed'
      path: '/class-feed'
      fullPath: '/class-feed'
      preLoaderRoute: typeof ClassFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutional': {
      id: '/institutional'
      path: '/institutional'
      fullPath: '/institutional'
      preLoaderRoute: typeof InstitutionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulations': {
      id: '/simulations'
      path: '/simulations'
      fullPath: '/simulations'
      preLoaderRoute: typeof SimulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/demo/assets': {
      id: '/demo/assets'
      path: '/assets'
      fullPath: '/demo/assets'
      preLoaderRoute: typeof DemoAssetsRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/simulation': {
      id: '/demo/simulation'
      path: '/simulation'
      fullPath: '/demo/simulation'
      preLoaderRoute: typeof DemoSimulationRouteImport
      parentRoute: typeof DemoRoute
    }
    '/formula-lab/$topic': {
      id: '/formula-lab/$topic'
      path: '/formula-lab/$topic'
      fullPath: '/formula-lab/$topic'
      preLoaderRoute: typeof FormulaLabTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutional/$': {
      id: '/institutional/$'
      path: '/$'
      fullPath: '/institutional/$'
      preLoaderRoute: typeof InstitutionalSplatRouteImport
      parentRoute: typeof InstitutionalRoute
    }
    '/sandbox/$simulationId': {
      id: '/sandbox/$simulationId'
      path: '/sandbox/$simulationId'
      fullPath: '/sandbox/$simulationId'
      preLoaderRoute: typeof SandboxSimulationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation/$topic': {
      id: '/simulation/$topic'
      path: '/simulation/$topic'
      fullPath: '/simulation/$topic'
      preLoaderRoute: typeof SimulationTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulations/': {
      id: '/simulations/'
      path: '/'
      fullPath: '/simulations/'
      preLoaderRoute: typeof SimulationsIndexRouteImport
      parentRoute: typeof SimulationsRoute
    }
    '/simulations/create': {
      id: '/simulations/create'
      path: '/create'
      fullPath: '/simulations/create'
      preLoaderRoute: typeof SimulationsCreateRouteImport
      parentRoute: typeof SimulationsRoute
    }
    '/student/attendance': {
      id: '/student/attendance'
      path: '/student/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof StudentAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$classId': {
      id: '/subjects/$classId'
      path: '/subjects/$classId'
      fullPath: '/subjects/$classId'
      preLoaderRoute: typeof SubjectsClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/$classId/$subject': {
      id: '/chapters/$classId/$subject'
      path: '/chapters/$classId/$subject'
      fullPath: '/chapters/$classId/$subject'
      preLoaderRoute: typeof ChaptersClassIdSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$classId/$subject/$chapter': {
      id: '/topics/$classId/$subject/$chapter'
      path: '/topics/$classId/$subject/$chapter'
      fullPath: '/topics/$classId/$subject/$chapter'
      preLoaderRoute: typeof TopicsClassIdSubjectChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminSplatRoute: typeof AdminSplatRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSplatRoute: AdminSplatRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DemoRouteChildren {
  DemoAssetsRoute: typeof DemoAssetsRoute
  DemoSimulationRoute: typeof DemoSimulationRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoAssetsRoute: DemoAssetsRoute,
  DemoSimulationRoute: DemoSimulationRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

interface InstitutionalRouteChildren {
  InstitutionalSplatRoute: typeof InstitutionalSplatRoute
}

const InstitutionalRouteChildren: InstitutionalRouteChildren = {
  InstitutionalSplatRoute: InstitutionalSplatRoute,
}

const InstitutionalRouteWithChildren = InstitutionalRoute._addFileChildren(
  InstitutionalRouteChildren,
)

interface SimulationsRouteChildren {
  SimulationsCreateRoute: typeof SimulationsCreateRoute
  SimulationsIndexRoute: typeof SimulationsIndexRoute
}

const SimulationsRouteChildren: SimulationsRouteChildren = {
  SimulationsCreateRoute: SimulationsCreateRoute,
  SimulationsIndexRoute: SimulationsIndexRoute,
}

const SimulationsRouteWithChildren = SimulationsRoute._addFileChildren(
  SimulationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AiAgentRoute: AiAgentRoute,
  ClassFeedRoute: ClassFeedRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRouteWithChildren,
  InstitutionalRoute: InstitutionalRouteWithChildren,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  ParentRoute: ParentRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SimulationsRoute: SimulationsRouteWithChildren,
  TutorRoute: TutorRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  FormulaLabTopicRoute: FormulaLabTopicRoute,
  SandboxSimulationIdRoute: SandboxSimulationIdRoute,
  SimulationTopicRoute: SimulationTopicRoute,
  StudentAttendanceRoute: StudentAttendanceRoute,
  SubjectsClassIdRoute: SubjectsClassIdRoute,
  ChaptersClassIdSubjectRoute: ChaptersClassIdSubjectRoute,
  TopicsClassIdSubjectChapterRoute: TopicsClassIdSubjectChapterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
