/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiAgentRouteImport } from './routes/ai-agent'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InstitutionalRouteImport } from './routes/institutional'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as FormulaLabTopicRouteImport } from './routes/formula-lab.$topic'
import { Route as InstitutionalSplatRouteImport } from './routes/institutional.$'
import { Route as SandboxSimulationIdRouteImport } from './routes/sandbox.$simulationId'
import { Route as SimulationTopicRouteImport } from './routes/simulation.$topic'
import { Route as SubjectsClassIdRouteImport } from './routes/subjects.$classId'
import { Route as ChaptersClassIdSubjectRouteImport } from './routes/chapters.$classId.$subject'
import { Route as TopicsClassIdSubjectChapterRouteImport } from './routes/topics.$classId.$subject.$chapter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentRoute = AiAgentRouteImport.update({
  id: '/ai-agent',
  path: '/ai-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionalRoute = InstitutionalRouteImport.update({
  id: '/institutional',
  path: '/institutional',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulaLabTopicRoute = FormulaLabTopicRouteImport.update({
  id: '/formula-lab/$topic',
  path: '/formula-lab/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionalSplatRoute = InstitutionalSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => InstitutionalRoute,
} as any)
const SandboxSimulationIdRoute = SandboxSimulationIdRouteImport.update({
  id: '/sandbox/$simulationId',
  path: '/sandbox/$simulationId',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationTopicRoute = SimulationTopicRouteImport.update({
  id: '/simulation/$topic',
  path: '/simulation/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsClassIdRoute = SubjectsClassIdRouteImport.update({
  id: '/subjects/$classId',
  path: '/subjects/$classId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersClassIdSubjectRoute = ChaptersClassIdSubjectRouteImport.update({
  id: '/chapters/$classId/$subject',
  path: '/chapters/$classId/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsClassIdSubjectChapterRoute =
  TopicsClassIdSubjectChapterRouteImport.update({
    id: '/topics/$classId/$subject/$chapter',
    path: '/topics/$classId/$subject/$chapter',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-agent': typeof AiAgentRoute
  '/dashboard': typeof DashboardRoute
  '/institutional': typeof InstitutionalRouteWithChildren
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tutor': typeof TutorRoute
  '/formula-lab/$topic': typeof FormulaLabTopicRoute
  '/institutional/$': typeof InstitutionalSplatRoute
  '/sandbox/$simulationId': typeof SandboxSimulationIdRoute
  '/simulation/$topic': typeof SimulationTopicRoute
  '/subjects/$classId': typeof SubjectsClassIdRoute
  '/chapters/$classId/$subject': typeof ChaptersClassIdSubjectRoute
  '/topics/$classId/$subject/$chapter': typeof TopicsClassIdSubjectChapterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-agent': typeof AiAgentRoute
  '/dashboard': typeof DashboardRoute
  '/institutional': typeof InstitutionalRouteWithChildren
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tutor': typeof TutorRoute
  '/formula-lab/$topic': typeof FormulaLabTopicRoute
  '/institutional/$': typeof InstitutionalSplatRoute
  '/sandbox/$simulationId': typeof SandboxSimulationIdRoute
  '/simulation/$topic': typeof SimulationTopicRoute
  '/subjects/$classId': typeof SubjectsClassIdRoute
  '/chapters/$classId/$subject': typeof ChaptersClassIdSubjectRoute
  '/topics/$classId/$subject/$chapter': typeof TopicsClassIdSubjectChapterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-agent': typeof AiAgentRoute
  '/dashboard': typeof DashboardRoute
  '/institutional': typeof InstitutionalRouteWithChildren
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tutor': typeof TutorRoute
  '/formula-lab/$topic': typeof FormulaLabTopicRoute
  '/institutional/$': typeof InstitutionalSplatRoute
  '/sandbox/$simulationId': typeof SandboxSimulationIdRoute
  '/simulation/$topic': typeof SimulationTopicRoute
  '/subjects/$classId': typeof SubjectsClassIdRoute
  '/chapters/$classId/$subject': typeof ChaptersClassIdSubjectRoute
  '/topics/$classId/$subject/$chapter': typeof TopicsClassIdSubjectChapterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-agent'
    | '/dashboard'
    | '/institutional'
    | '/library'
    | '/login'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/tutor'
    | '/formula-lab/$topic'
    | '/institutional/$'
    | '/sandbox/$simulationId'
    | '/simulation/$topic'
    | '/subjects/$classId'
    | '/chapters/$classId/$subject'
    | '/topics/$classId/$subject/$chapter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-agent'
    | '/dashboard'
    | '/institutional'
    | '/library'
    | '/login'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/tutor'
    | '/formula-lab/$topic'
    | '/institutional/$'
    | '/sandbox/$simulationId'
    | '/simulation/$topic'
    | '/subjects/$classId'
    | '/chapters/$classId/$subject'
    | '/topics/$classId/$subject/$chapter'
  id:
    | '__root__'
    | '/'
    | '/ai-agent'
    | '/dashboard'
    | '/institutional'
    | '/library'
    | '/login'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/tutor'
    | '/formula-lab/$topic'
    | '/institutional/$'
    | '/sandbox/$simulationId'
    | '/simulation/$topic'
    | '/subjects/$classId'
    | '/chapters/$classId/$subject'
    | '/topics/$classId/$subject/$chapter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAgentRoute: typeof AiAgentRoute
  DashboardRoute: typeof DashboardRoute
  InstitutionalRoute: typeof InstitutionalRouteWithChildren
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TutorRoute: typeof TutorRoute
  FormulaLabTopicRoute: typeof FormulaLabTopicRoute
  SandboxSimulationIdRoute: typeof SandboxSimulationIdRoute
  SimulationTopicRoute: typeof SimulationTopicRoute
  SubjectsClassIdRoute: typeof SubjectsClassIdRoute
  ChaptersClassIdSubjectRoute: typeof ChaptersClassIdSubjectRoute
  TopicsClassIdSubjectChapterRoute: typeof TopicsClassIdSubjectChapterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agent': {
      id: '/ai-agent'
      path: '/ai-agent'
      fullPath: '/ai-agent'
      preLoaderRoute: typeof AiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutional': {
      id: '/institutional'
      path: '/institutional'
      fullPath: '/institutional'
      preLoaderRoute: typeof InstitutionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formula-lab/$topic': {
      id: '/formula-lab/$topic'
      path: '/formula-lab/$topic'
      fullPath: '/formula-lab/$topic'
      preLoaderRoute: typeof FormulaLabTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutional/$': {
      id: '/institutional/$'
      path: '/$'
      fullPath: '/institutional/$'
      preLoaderRoute: typeof InstitutionalSplatRouteImport
      parentRoute: typeof InstitutionalRoute
    }
    '/sandbox/$simulationId': {
      id: '/sandbox/$simulationId'
      path: '/sandbox/$simulationId'
      fullPath: '/sandbox/$simulationId'
      preLoaderRoute: typeof SandboxSimulationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation/$topic': {
      id: '/simulation/$topic'
      path: '/simulation/$topic'
      fullPath: '/simulation/$topic'
      preLoaderRoute: typeof SimulationTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$classId': {
      id: '/subjects/$classId'
      path: '/subjects/$classId'
      fullPath: '/subjects/$classId'
      preLoaderRoute: typeof SubjectsClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/$classId/$subject': {
      id: '/chapters/$classId/$subject'
      path: '/chapters/$classId/$subject'
      fullPath: '/chapters/$classId/$subject'
      preLoaderRoute: typeof ChaptersClassIdSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$classId/$subject/$chapter': {
      id: '/topics/$classId/$subject/$chapter'
      path: '/topics/$classId/$subject/$chapter'
      fullPath: '/topics/$classId/$subject/$chapter'
      preLoaderRoute: typeof TopicsClassIdSubjectChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InstitutionalRouteChildren {
  InstitutionalSplatRoute: typeof InstitutionalSplatRoute
}

const InstitutionalRouteChildren: InstitutionalRouteChildren = {
  InstitutionalSplatRoute: InstitutionalSplatRoute,
}

const InstitutionalRouteWithChildren = InstitutionalRoute._addFileChildren(
  InstitutionalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAgentRoute: AiAgentRoute,
  DashboardRoute: DashboardRoute,
  InstitutionalRoute: InstitutionalRouteWithChildren,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TutorRoute: TutorRoute,
  FormulaLabTopicRoute: FormulaLabTopicRoute,
  SandboxSimulationIdRoute: SandboxSimulationIdRoute,
  SimulationTopicRoute: SimulationTopicRoute,
  SubjectsClassIdRoute: SubjectsClassIdRoute,
  ChaptersClassIdSubjectRoute: ChaptersClassIdSubjectRoute,
  TopicsClassIdSubjectChapterRoute: TopicsClassIdSubjectChapterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
