"""
normalizers.py
==============
Defensive normalization module for EduSim backend.

This module intercepts imperfect, inconsistent, or malformed inputs generated by 
AI models (or legacy configurations) and cleans them into structured, normalized 
dicts compatible with Pydantic schemas.

It performs data healing for gravity vectors, position coordinates, units strings (like 
"5kg" -> 5), and various nested dictionary objects.
"""


from __future__ import annotations
import re
from typing import Any, Dict, List, Optional, Union


def normalize_number(val: Any, default_val: float = 0.0) -> float:
    """
    Normalizes a numerical value, extracting numbers from strings with units 
    (e.g., "5.2 kg" -> 5.2, "100px" -> 100.0, None -> default_val).
    """
    if val is None:
        return default_val
    if isinstance(val, (int, float)):
        return float(val)
    
    # Strip whitespace and commas
    cleaned = str(val).strip().replace(",", "")
    
    # Check if empty
    if not cleaned:
        return default_val
        
    try:
        # Regex to extract float or integer component from unit strings
        match = re.search(r"[-+]?\d*\.\d+|\d+", cleaned)
        if match:
            return float(match.group())
    except ValueError:
        pass
        
    return default_val


def normalize_vector_2d(val: Any, default_x: float = 0.0, default_y: float = 0.0) -> Dict[str, float]:
    """
    Normalizes coordinates / vectors into a standard Dict[x, y].
    Supports:
      - [x, y] list/tuple
      - {"x": val, "y": val} dictionary
      - Scalar number (sets x=val, y=val)
      - None / malformed values
    """
    if val is None:
        return {"x": default_x, "y": default_y}
        
    if isinstance(val, (list, tuple)):
        x = normalize_number(val[0]) if len(val) > 0 else default_x
        y = normalize_number(val[1]) if len(val) > 1 else default_y
        return {"x": x, "y": y}
        
    if isinstance(val, dict):
        # Case insensitive check
        x_val = val.get("x") if "x" in val else val.get("X", default_x)
        y_val = val.get("y") if "y" in val else val.get("Y", default_y)
        return {"x": normalize_number(x_val), "y": normalize_number(y_val)}
        
    if isinstance(val, (int, float)):
        num = float(val)
        return {"x": num, "y": num}
        
    # Attempt parsing string form like "[10, 20]" or "(10, 20)"
    if isinstance(val, str):
        cleaned = val.strip("[]() ")
        parts = cleaned.split(",")
        if len(parts) >= 2:
            return {
                "x": normalize_number(parts[0].strip()),
                "y": normalize_number(parts[1].strip())
            }
            
    return {"x": default_x, "y": default_y}


def normalize_gravity(val: Any) -> Dict[str, Any]:
    """
    Normalizes environment gravity configuration.
    Formats supported:
      - Raw gravity scalar (e.g. 9.8 -> vertical gravity x=0, y=9.8, scale=1.0)
      - Raw gravity vector list [x, y]
      - Gravity dictionary (maps partial keys to GravityField model)
    """
    from app.src.modules.sandbox.initialization.defaults import (
        DEFAULT_GRAVITY_X,
        DEFAULT_GRAVITY_Y,
        DEFAULT_GRAVITY_SCALE
    )

    if val is None:
        return {"x": DEFAULT_GRAVITY_X, "y": DEFAULT_GRAVITY_Y, "scale": DEFAULT_GRAVITY_SCALE}
        
    # Gravity represented as a scalar (standard Newtonian vertical gravity)
    if isinstance(val, (int, float)):
        return {"x": 0.0, "y": float(val), "scale": 1.0}
        
    if isinstance(val, (list, tuple)):
        vec = normalize_vector_2d(val, DEFAULT_GRAVITY_X, DEFAULT_GRAVITY_Y)
        return {"x": vec["x"], "y": vec["y"], "scale": 1.0}
        
    if isinstance(val, dict):
        x = normalize_number(val.get("x", val.get("X", DEFAULT_GRAVITY_X)))
        y = normalize_number(val.get("y", val.get("Y", DEFAULT_GRAVITY_Y)))
        scale = normalize_number(val.get("scale", DEFAULT_GRAVITY_SCALE), DEFAULT_GRAVITY_SCALE)
        return {"x": x, "y": y, "scale": scale}
        
    return {"x": DEFAULT_GRAVITY_X, "y": DEFAULT_GRAVITY_Y, "scale": DEFAULT_GRAVITY_SCALE}


def normalize_object_geometry(obj_dict: Dict[str, Any]) -> Dict[str, Any]:
    """
    Heals geometric definition inconsistencies on SandboxObjects.
    """
    shape_type = str(obj_dict.get("shape_type", "")).strip().lower()
    
    # Try to guess shape if missing
    if not shape_type:
        if obj_dict.get("radius") is not None:
            shape_type = "circle"
        elif obj_dict.get("width") is not None or obj_dict.get("height") is not None:
            shape_type = "rectangle"
        elif obj_dict.get("vertices") is not None:
            shape_type = "polygon"
        else:
            shape_type = "circle" # Ultimate fallback
            
    obj_dict["shape_type"] = shape_type
    
    # Handle radius/size fallbacks
    if shape_type == "circle":
        r = obj_dict.get("radius")
        if r is None:
            # Maybe specified as size or diameter
            r = obj_dict.get("size", obj_dict.get("diameter", 40.0))
            if r is not None:
                r = normalize_number(r) / (2.0 if "diameter" in obj_dict else 1.0)
        obj_dict["radius"] = normalize_number(r, 20.0)
        
    elif shape_type == "rectangle":
        w = normalize_number(obj_dict.get("width", obj_dict.get("size", 40.0)), 40.0)
        h = normalize_number(obj_dict.get("height", obj_dict.get("size", 40.0)), 40.0)
        obj_dict["width"] = w
        obj_dict["height"] = h
        
    elif shape_type == "polygon":
        raw_verts = obj_dict.get("vertices", [])
        verts = []
        if isinstance(raw_verts, list):
            for v in raw_verts:
                verts.append(normalize_vector_2d(v))
        obj_dict["vertices"] = verts
        
    return obj_dict


def normalize_sandbox_payload(payload: Dict[str, Any]) -> Dict[str, Any]:
    """
    Performs comprehensive structural normalization of a raw input payload.
    """
    normalized = {}

    # 1. Metadata
    meta = payload.get("metadata", {})
    if not isinstance(meta, dict):
        meta = {}
    normalized["metadata"] = meta

    # 2. Environment
    env = payload.get("environment", {})
    if not isinstance(env, dict):
        env = {}
        
    # Gravity sub-normalization
    env["gravity"] = normalize_gravity(env.get("gravity"))
    
    # Wind
    wind = env.get("wind", {})
    if not isinstance(wind, dict):
        wind = {}
    wind["enabled"] = bool(wind.get("enabled", False))
    wind["magnitude"] = normalize_number(wind.get("magnitude", 0.0))
    wind["direction_deg"] = normalize_number(wind.get("direction_deg", 0.0))
    wind["turbulence"] = normalize_number(wind.get("turbulence", 0.0))
    env["wind"] = wind
    
    # Atmosphere
    atm = env.get("atmosphere", {})
    if not isinstance(atm, dict):
        atm = {}
    env["atmosphere"] = atm
    
    normalized["environment"] = env

    # 3. Objects
    raw_objects = payload.get("objects", [])
    if not isinstance(raw_objects, list):
        raw_objects = []
        
    normalized_objects = []
    for idx, obj in enumerate(raw_objects):
        if not isinstance(obj, dict):
            continue
        # Ensure a valid ID
        obj_id = str(obj.get("id", f"object_{idx+1}")).strip()
        obj["id"] = obj_id
        
        # Geometry normalization
        obj = normalize_object_geometry(obj)
        
        # Heals nested properties
        for key in ["physics", "visuals", "runtime", "education"]:
            if key not in obj or not isinstance(obj[key], dict):
                obj[key] = {}

        # Heal physics properties defensively to prevent Pydantic contract failures
        phys = obj["physics"]
        if "mass" in phys:
            m_val = normalize_number(phys["mass"], 1.0)
            phys["mass"] = m_val if m_val > 0.0 else 1.0
        
        if "restitution" in phys:
            rest = normalize_number(phys["restitution"], 0.5)
            phys["restitution"] = max(0.0, min(1.0, rest))
            
        if "friction" in phys:
            fric = normalize_number(phys["friction"], 0.1)
            phys["friction"] = max(0.0, fric)

        if "friction_static" in phys:
            fric_s = normalize_number(phys["friction_static"], 0.05)
            phys["friction_static"] = max(0.0, fric_s)

        if "density" in phys and phys["density"] is not None:
            dens = normalize_number(phys["density"], 1.0)
            phys["density"] = dens if dens > 0.0 else None

        normalized_objects.append(obj)
        
    normalized["objects"] = normalized_objects

    # 4. Constraints
    raw_constraints = payload.get("constraints", [])
    if not isinstance(raw_constraints, list):
        raw_constraints = []
        
    normalized_constraints = []
    for idx, const in enumerate(raw_constraints):
        if not isinstance(const, dict):
            continue
        c_id = str(const.get("id", f"constraint_{idx+1}")).strip()
        const["id"] = c_id
        
        # Ensure anchor definitions exist
        for side in ["anchor_a", "anchor_b"]:
            if side not in const or not isinstance(const[side], dict):
                const[side] = {"body_id": None, "offset": {"x": 0.0, "y": 0.0}}
            else:
                anchor = const[side]
                anchor["offset"] = normalize_vector_2d(anchor.get("offset"))
                if "world_point" in anchor and anchor["world_point"]:
                    anchor["world_point"] = normalize_vector_2d(anchor["world_point"])
        
        normalized_constraints.append(const)
        
    normalized["constraints"] = normalized_constraints

    # 5. Passthrough containers for other collections
    for key in ["relationships", "observables", "controls"]:
        items = payload.get(key, [])
        normalized[key] = items if isinstance(items, list) else []

    return normalized
