"""Add curriculum classes"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3edceb2dcbf'
down_revision = '0001_create_persistence_schema'
branch_labels = None
depends_on = None


def safe_drop_index(index_name: str, table_name: str) -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    indexes = [idx['name'] for idx in inspector.get_indexes(table_name)]
    if index_name in indexes:
        op.drop_index(index_name, table_name=table_name)

def safe_drop_column(table_name: str, column_name: str) -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    if column_name in columns:
        op.drop_column(table_name, column_name)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    safe_drop_index('ix_chapters_class_name', 'chapters')
    safe_drop_column('chapters', 'class_name')
    op.add_column('subjects', sa.Column('class_id', sa.Integer(), nullable=False))
    safe_drop_index('ix_subjects_code', 'subjects')
    op.create_index(op.f('ix_subjects_code'), 'subjects', ['code'], unique=False)
    op.create_index(op.f('ix_subjects_class_id'), 'subjects', ['class_id'], unique=False)
    op.create_unique_constraint('uq_class_subject_code', 'subjects', ['class_id', 'code'])
    op.create_foreign_key(None, 'subjects', 'classes', ['class_id'], ['id'], ondelete='CASCADE')
    op.add_column('topics', sa.Column('has_simulation', sa.Boolean(), nullable=True))
    op.add_column('topics', sa.Column('simulation_route', sa.String(length=255), nullable=True))
    safe_drop_index('ix_user_sessions_session_key', 'user_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_sessions_session_key'), 'user_sessions', ['session_key'], unique=True)
    op.drop_column('topics', 'simulation_route')
    op.drop_column('topics', 'has_simulation')
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_constraint('uq_class_subject_code', 'subjects', type_='unique')
    op.drop_index(op.f('ix_subjects_class_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_code'), table_name='subjects')
    op.create_index(op.f('ix_subjects_code'), 'subjects', ['code'], unique=True)
    op.drop_column('subjects', 'class_id')
    op.add_column('chapters', sa.Column('class_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_chapters_class_name'), 'chapters', ['class_name'], unique=False)
    # ### end Alembic commands ###
