"""update_user_role_to_enum"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c01f90fa39c7'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age_group', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('institution_id', sa.UUID(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ADMIN', 'EDUCATOR', 'STUDENT', name='user_role', native_enum=False),
               nullable=False)
    op.create_foreign_key(None, 'users', 'institutions', ['institution_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'EDUCATOR', 'STUDENT', name='user_role', native_enum=False),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('users', 'institution_id')
    op.drop_column('users', 'age_group')
    # ### end Alembic commands ###
