"""add display_order"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8ab0c44fa40'
down_revision = 'b3edceb2dcbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('display_order', sa.Integer(), server_default='0', nullable=False))
    op.add_column('classes', sa.Column('display_order', sa.Integer(), server_default='0', nullable=False))
    op.add_column('subjects', sa.Column('display_order', sa.Integer(), server_default='0', nullable=False))
    op.add_column('topics', sa.Column('display_order', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'display_order')
    op.drop_column('subjects', 'display_order')
    op.drop_column('classes', 'display_order')
    op.drop_column('chapters', 'display_order')
    # ### end Alembic commands ###
