"""add unique constraints"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc62e10ff6d1'
down_revision = 'd8ab0c44fa40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_subject_chapter_name', 'chapters', ['subject_id', 'name'])
    op.create_unique_constraint('uq_chapter_topic_name', 'topics', ['chapter_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_chapter_topic_name', 'topics', type_='unique')
    op.drop_constraint('uq_subject_chapter_name', 'chapters', type_='unique')
    # ### end Alembic commands ###
